---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watcher
rules:
- apiGroups: [""] # core API group
  resources: ["pods", "namespaces", "secrets"]
  verbs: ["get", "watch", "list"]
