---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: theo
  name: watcher
rules:
  - apiGroups: [""]
    resources: ["pods","namespace", "secrets"]
    verbs: ["get", "watch", "list"]
