---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watchrolebinding
  namespace: theo
subjects:
  - kind: ServiceAccount
    name: watcher
    namespace: theo
roleRef:
  kind: Role
  name: watcher
  apiGroup: rbac.authorization.k8s.io
